# Config for MT training
#
save_data: practicum2/models/te_to_en_wiki
  #
# Corpus opts:
data:
    train:
        path_src: practicum2/data/en_te/preProcessedwiki/wikimatrix-en-te.bpe.te
        path_tgt: practicum2/data/en_te/preProcessedwiki/wikimatrix-en-te.bpe.en
    valid:
        path_src: practicum2/data/en_te/preProcessedwiki/dev.bpe.en
        path_tgt: practicum2/data/en_te/preProcessedwiki/dev.bpe.te

subword_nbest: 1
subword_alpha: 0.0
#### Filter
src_seq_length: 150
tgt_seq_length: 150

# silently ignore empty lines in the data
skip_empty_level: silent


# # Vocab opts
# ### vocab:
src_vocab: practicum2/data/en_te/preProcessedwiki/vocab_wiki.te
tgt_vocab: practicum2/data/en_te/preProcessedwiki/vocab_wiki.en
src_vocab_size: 45954
tgt_vocab_size: 46012
vocab_size_multiple: 8
src_words_min_frequency: 1
tgt_words_min_frequency: 1
#share_vocab: True

# # Model training parameters

# General opts
save_model: practicum2/models/te_to_en_wiki
keep_checkpoint: 60
save_checkpoint_steps: 10000
average_decay: 0.0005
seed: 1234
report_every: 100
train_steps: 150000
valid_steps: 10000

# Batching
queue_size: 1024
bucket_size: 32768
pool_factor: 8192
world_size: 1
gpu_ranks: [0]
batch_type: "tokens"
batch_size: 3072
valid_batch_size: 5120
batch_size_multiple: 1
max_generator_batches: 0
accum_count: [2]
accum_steps: [0]

# Optimization
model_dtype: "fp32"
optim: "adam"
learning_rate: 2.0
warmup_steps: 6000
decay_method: "noam"
adam_beta1: 0.9
adam_beta2: 0.98
max_grad_norm: 0
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: "tokens"

# Model
encoder_type: transformer
decoder_type: transformer
enc_layers: 6
dec_layers: 6
heads: 8
rnn_size: 512
word_vec_size: 512
transformer_ff: 2048
dropout_steps: [0]
dropout: [0.1]
attention_dropout: [0.1]
#share_decoder_embeddings: true
#share_embeddings: true
position_encoding: true
